language: bash
services: docker
env:
  - VERSION=10.3
  - VERSION=10.2
  - VERSION=10.1
  - VERSION=10.0
  - VERSION=5.5

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - image="mariadb-server-docker:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/mariadb-docker-images/test/run.sh "$image"
    )

after_script:
- docker images
