language: bash
services: docker
env:
  - VERSION=5.5
  - VERSION=10.3
  - VERSION=10.2
  - VERSION=10.1
  - VERSION=10.0

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mariadb-docker-images:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
- docker images